apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-ms-user
  labels:
    app: fcg-ms-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-ms-user
  template:
    metadata:
      labels:
        app: fcg-ms-user
    spec:
      containers:
        - name: fcg-ms-user
          image: 399668701651.dkr.ecr.us-east-1.amazonaws.com/fcg-user:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: fcg-ms-user-secret
                  key: ConnectionStrings__DefaultConnection
            - name: UserNotification__Uri
              valueFrom:
                secretKeyRef:
                  name: fcg-ms-user-secret
                  key: UserNotification__Uri
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: fcg-ms-user-service
  labels:
    app: fcg-ms-user
spec:
  type: LoadBalancer
  selector:
    app: fcg-ms-user
  ports:
    - port: 80
      targetPort: 80
