apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-user
  labels:
    app: fcg-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-user
  template:
    metadata:
      labels:
        app: fcg-user
    spec:
      containers:
        - name: fcg-user
          image: 399668701651.dkr.ecr.us-east-1.amazonaws.com/fcg-user:latest
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: fcg-ms-user-secret
                  key: ConnectionStrings__DefaultConnection
            - name: UserNotification__Uri
              valueFrom:
                secretKeyRef:
                  name: fcg-ms-user-secret
                  key: UserNotification__Uri
          readinessProbe:
            httpGet:
              path: /swagger/index.html
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fcg-user-service
  labels:
    app: fcg-user
spec:
  type: LoadBalancer
  selector:
    app: fcg-user
  ports:
    - port: 8080
      targetPort: 8080
